env:
  es2020: true
  browser: true
  jest: true
  node: true
root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  # plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules: # In order of https:#eslint.org/docs/rules

  # --------------------------------------------
  # Possible Errors
  # --------------------------------------------

  for-direction: error # eslint:recommended
  getter-return: error # eslint:recommended
  no-async-promise-executor: error #eslint:recommended
  no-await-in-loop: off
  no-compare-neg-zero: error # eslint:recommended
  no-cond-assign: off # eslint:recommended
  no-console: error # eslint:recommended
  no-constant-condition: error # eslint:recommended
  no-control-regex: error # eslint:recommended
  no-debugger: error # eslint:recommended
  no-dupe-args: error # eslint:recommended
  no-dupe-keys: error # eslint:recommended
  no-duplicate-case: error # eslint:recommended
  no-empty: error # eslint:recommended
  no-empty-character-class: error # eslint:recommended
  no-ex-assign: error # eslint:recommended
  no-extra-boolean-cast: error # eslint:recommended
  no-extra-parens: off
  no-extra-semi: error # eslint:recommended
  no-func-assign: error # eslint:recommended
  no-inner-declarations: error # eslint:recommended
  no-invalid-regexp: error # eslint:recommended
  no-irregular-whitespace: # eslint:recommended
    - error
    - skipStrings: true
      skipComments: true
      skipTemplates: true
  no-misleading-character-class: error # eslint:recommended
  no-obj-calls: error # eslint:recommended
  no-prototype-builtins: error # eslint:recommended
  no-regex-spaces: error # eslint:recommended
  no-sparse-arrays: error # eslint:recommended
  no-template-curly-in-string: off
  no-unexpected-multiline: error # eslint:recommended
  no-unreachable: error # eslint:recommended
  no-unsafe-finally: error # eslint:recommended
  no-unsafe-negation: error # eslint:recommended
  require-atomic-updates: warn # eslint:recommended
  use-isnan: error # eslint:recommended

  
  # --------------------------------------------
  # Best Practices
  # --------------------------------------------

  accessor-pairs: off
  array-callback-return: off
  block-scoped-var: off
  class-methods-use-this: off
  complexity: warn
  consistent-return: off
  curly: [ error, multi-or-nest, consistent ]
  default-case: error
  dot-location: [ error, property ]
  dot-notation: error
  eqeqeq: 
    - error
    - always
    - null: ignore
  guard-for-in: error
  no-alert: off
  no-caller: error
  no-case-declarations: error # eslint:recommended
  no-div-regex: off
  no-else-return: off
  no-empty-function: off
  no-empty-pattern: off # eslint:recommended
  no-eq-null: off
  no-eval: off
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: off
  no-fallthrough: error # eslint:recommended
  no-floating-decimal: off
  no-global-assign: off
  no-implicit-coercion: off
  no-implicit-globals: off
  no-implied-eval: off
  no-invalid-this: error
  no-iterator: off
  no-labels: off
  no-lone-blocks: off
  no-loop-func: off
  no-magic-numbers: off
  no-multi-spaces: error
  no-multi-str: error
  no-new: off
  no-new-func: off
  no-new-wrappers: error
  no-octal: error # eslint:recommended
  no-octal-escape: off
  no-param-reassign: off
  no-proto: off
  no-redeclare: error # eslint:recommended
  no-restricted-properties: off
  no-return-assign: off
  no-script-url: off
  no-self-assign: error # eslint:recommended
  no-self-compare: off
  no-sequences: off
  no-throw-literal: error # eslint:recommended
  no-unmodified-loop-condition: off
  no-unused-expressions: off
  no-unused-labels: error # eslint:recommended
  no-useless-call: error
  no-useless-catch: error # eslint:recommended
  no-useless-concat: error
  no-useless-escape: error # eslint:recommended  
  no-void: off
  no-warning-comments: off
  no-with: error # eslint:recommended
  prefer-promise-reject-errors: error
  radix: off
  require-await: off
  vars-on-top: off
  wrap-iife: off
  yoda: off

  # --------------------------------------------
  # Strict Mode
  # -----------------------------------------

  strict: off

  # ---------------------------------------
  # Variables
  # ---------------------------------------

  init-declarations: off
  no-catch-shadow: off
  no-delete-var: error # eslint:recommended
  no-label-var: off
  no-restricted-globals: off
  no-shadow: off
  no-shadow-restricted-names: error # eslint:recommended
  no-undef: error # eslint:recommended
  no-undef-init: off
  no-undefined: off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': off
  no-use-before-define: off

  
  # -------------------------------------------------
  # Node.js and CommonJS
  # -------------------------------------------------
    
  callback-return: off
  global-require: off
  handle-callback-err: off
  no-buffer-constructor: off
  no-mixed-requires: off
  no-new-require: off
  no-path-concat: off
  no-process-env: off
  no-process-exit: off
  no-restricted-modules: off
  no-sync: off


  # -------------------------------------------------
  # Stylistic Issues
  # ----------------------------------------------

  array-bracket-newline: error # eslint:recommended
  array-bracket-spacing: [error, always]
  array-element-newline: [error, consistent] # eslint:recommended
  block-spacing: [error, always]
  brace-style: error
  camelcase: off
  '@typescript-eslint/camelcase': off # Allow snake_case vars
  capitalized-comments: off
  comma-dangle:
      - error
      - arrays: always-multiline
        objects: always-multiline
        functions: ignore
  comma-spacing: error
  comma-style: error
  computed-property-spacing: off
  consistent-this: off
  eol-last: error
  func-call-spacing: error
  func-name-matching: off
  func-names: off
  func-style: off
  id-blacklist: off
  id-length: off
  id-match: off
  indent: 
    - error
    - 2
    - ignoredNodes:
      - 'TemplateLiteral *'
      SwitchCase: 2
  jsx-quotes: off
  key-spacing: error
  keyword-spacing: error
  line-comment-position: off
  linebreak-style: error
  lines-around-comment: off
  max-depth: off
  max-len: off
  max-lines: off
  max-nested-callbacks: off
  max-params: off
  max-statements: off
  max-statements-per-line: off
  multiline-ternary: off
  new-cap: off # Needs a typescript version
  new-parens: [error, never]
  newline-per-chained-call: off
  no-array-constructor: error
  no-bitwise: off
  no-continue: off
  no-inline-comments: off
  no-lonely-if: off
  no-mixed-operators: off
  no-mixed-spaces-and-tabs: error # eslint:recommended
  no-multi-assign: off
  no-multiple-empty-lines: error
  no-negated-condition: off
  no-nested-ternary: off
  no-new-object: error
  no-plusplus: off
  no-restricted-syntax: off
  no-tabs: error
  no-ternary: off
  no-trailing-spaces: 
    - error
    - skipBlankLines: true
  no-underscore-dangle: off
  no-unneeded-ternary: off
  no-whitespace-before-property: off
  nonblock-statement-body-position: off
  object-curly-newline: off
  object-curly-spacing: [error, always]
  object-property-newline: off
  one-var: off
  one-var-declaration-per-line: error
  operator-assignment: off
  operator-linebreak: 
    - error
    - after
    - overrides:
        "?": ignore 
        ":": ignore
  padded-blocks: off
  padding-line-between-statements: off
  quote-props: [error, as-needed]
  quotes: [error, single]
  semi: error
  semi-spacing: error
  semi-style: off
  sort-keys: off
  sort-vars: off
  space-before-blocks: error
  space-before-function-paren: [error, always]
  space-in-parens: [error, always]
  space-infix-ops: off
  space-unary-ops: off # Ideally would enforce space after unary ! and no space after other non-word unary operators
  spaced-comment: [error, always]
  switch-colon-spacing: error
  template-tag-spacing: off
  unicode-bom: off
  wrap-regex: off


  # ------------------------------------------
  # ECMAScript 6
  # ------------------------------------------
    
  arrow-body-style: off
  arrow-parens: [error, as-needed]
  arrow-spacing: error
  constructor-super: error # eslint:recommended
  generator-star-spacing: [error, both]
  no-class-assign: off
  no-confusing-arrow: off
  no-const-assign: error # eslint:recommended
  no-dupe-class-members: error # eslint:recommended
  no-duplicate-imports: error 
  no-new-symbol: error # eslint:recommended
  no-restricted-imports: off
  no-this-before-super: error # eslint:recommended
  no-useless-computed-key: off
  no-useless-constructor: off
  no-useless-rename: off
  no-var: error
  object-shorthand: off
  prefer-arrow-callback: off
  prefer-const: error
  prefer-destructuring: off
  prefer-numeric-literals: off
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: off
  require-yield: error # eslint:recommended
  rest-spread-spacing: error
  sort-imports: off
  symbol-description: off
  template-curly-spacing: [error, never] 
  yield-star-spacing: [error, both]

  '@typescript-eslint/consistent-type-assertions': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-use-before-define': off

  '@typescript-eslint/no-non-null-assertion': off

  'jest/expect-expect':
    - error
    - assertFunctionNames:
      - expect
      - request.*.expect

  'import/no-anonymous-default-export': off
